# Generated by Django 5.0.2 on 2024-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupportBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportusers',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
