# Generated by Django 5.0.2 on 2024-03-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupportBot', '0003_adminsid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminsid',
            table='admins_id',
        ),
    ]
