version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_web
    command: /start
    volumes:
      - .:/app
    expose:
      - 80
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - bot

  bot:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: aiogram_bot
    command: python /bot/Bot/main.py
    volumes:
      - .:/bot
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tiiamefeedback
      - POSTGRES_PASSWORD=1253
    ports:
      - "5432:5432"

volumes:
  postgres_data: