# Generated by Django 5.0.1 on 2024-02-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': "Yangilik va e'lonlar"},
        ),
    ]
