# Generated by Django 5.0.1 on 2024-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='day',
            field=models.IntegerField(choices=[('0', 'Dushanba'), ('1', 'Seshanba'), ('2', 'Chorshanba'), ('3', 'Payshanba'), ('4', 'Juma'), ('5', 'Shanba')]),
        ),
    ]
