# Generated by Django 5.0.1 on 2024-02-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated_at',
        ),
    ]
