# Generated by Django 5.0.1 on 2024-01-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0004_alter_student_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='day',
            field=models.CharField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], max_length=10),
        ),
    ]
