# Generated by Django 5.0.1 on 2024-02-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0004_alter_student_telegram_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('group', 'lesson', 'teacher', 'day', 'start_time')},
        ),
    ]
