# Generated by Django 5.0.1 on 2024-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0006_remove_teacher_degree_alter_classschedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_num',
            field=models.IntegerField(),
        ),
    ]
