# Generated by Django 5.0.1 on 2024-03-08 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_num', models.IntegerField()),
                ('course_num', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('uz', "O'zbek guruh"), ('eng', 'Ingliz guruh'), ('rus', 'Rus guruh')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fanlar',
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Uztozlar',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('course_num', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.group')),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_for_teacher', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.teacher')),
            ],
            options={
                'verbose_name_plural': 'Baholar',
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')])),
                ('start_time', models.CharField(choices=[('08:30:00', '1-PARA, 08:30'), ('09:30:00', '2-PARA, 09:30'), ('10:30:00', '3-PARA, 10:30'), ('11:30:00', '4-PARA, 11:30'), ('12:30:00', '5-PARA, 12:30'), ('13:30:00', '6-PARA, 13:30'), ('14:30:00', '7-PARA, 14:30'), ('15:30:00', '8-PARA, 15:30'), ('16:30:00', '9-PARA, 16:30')], max_length=15)),
                ('end_time', models.CharField(blank=True, max_length=15, null=True)),
                ('room', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackbot.teacher')),
            ],
            options={
                'verbose_name_plural': 'Dars jadvali',
                'db_table': 'class_schedule',
            },
        ),
    ]
