# Generated by Django 5.0.1 on 2024-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0003_group_created_at_group_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
