# Generated by Django 5.0.1 on 2024-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0008_remove_teacher_first_name_remove_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='room',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
