# Generated by Django 5.0.1 on 2024-03-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0009_alter_classschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.CharField(choices=[('08:30:00', '1-PARA, 08:30'), ('09:30:00', '2-PARA, 10:00'), ('10:30:00', '3-PARA, 11:30'), ('11:30:00', '4-PARA, 13:00'), ('12:30:00', '5-PARA, 13:30'), ('13:30:00', '6-PARA, 15:00'), ('14:30:00', '7-PARA, 16:30'), ('15:30:00', '8-PARA, 16:30'), ('16:30:00', '9-PARA, 16:30')], max_length=15),
        ),
    ]
