# Generated by Django 5.0.1 on 2024-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0010_alter_classschedule_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'support_users',
            },
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.CharField(choices=[('08:30:00', '1-PARA, 08:30'), ('09:30:00', '2-PARA, 09:30'), ('10:30:00', '3-PARA, 10:30'), ('11:30:00', '4-PARA, 11:30'), ('12:30:00', '5-PARA, 12:30'), ('13:30:00', '6-PARA, 13:30'), ('14:30:00', '7-PARA, 14:30'), ('15:30:00', '8-PARA, 15:30'), ('16:30:00', '9-PARA, 16:30')], max_length=15),
        ),
    ]
