# Generated by Django 5.0.1 on 2024-03-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0011_supportusers_alter_classschedule_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportusers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supportusers',
            name='updated_at',
        ),
    ]
