# Generated by Django 5.0.1 on 2024-03-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0012_remove_supportusers_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('message_date', models.DateField()),
                ('message_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Kunlik xabarlar',
                'db_table': 'daily_messages',
            },
        ),
    ]
