# Generated by Django 5.0.1 on 2024-03-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackbot', '0013_dailymessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyMessages',
        ),
        migrations.DeleteModel(
            name='SupportUsers',
        ),
    ]
