uzbek = {
    "greeting": "Assalomu alaykum!",
    "login_prompt": "*Iltimos, shaxsiy login raqamingizni yuboring❗*",
    "password_prompt": "*Iltimos, parolingizni yuboring❗*",
    "login_success": "Ro'xatdan o'tish muvaffaqiyatli amalga oshirildi❗",
    "already_registered": "*Siz allaqachon ro'yxatdan o'tgansiz❗*",
    "user_exists": "*Bunday foydalanuvchi mavjud❗*\n\nQayta urunish uchun /start buyrug'ini bosing.",
    "login_error": "ID yoki parolingiz xato iltimos qaytadan urunib ko'ring❗\n\nQayta urunish uchun /start buyrug'ini bosing",
    "about_not_registered": "Siz ro'yxatdan o'tmagansiz❗ Iltimos, /start buyrug'ini bosing.",
    "help_message": "Ushbu bot ta’lim sifatini nazorat qilish va ustozlarga baho berish uchun mo‘ljallangan.\n\nBotdan foydalanish uchun quyidagi buyruqlardan foydalaning:\n\n/start - Botni ishga tushirish\n/about - O‘z ma’lumotlaringizni ko‘rish\n/tutorial - Botdan foydalanish uchun qo‘llanma\n/help - Yordam\n/lang - Tilni o'zgartirish\n\n*Bunday foydalanuvchi mavjud* xabari kelsa demak sizga tegishli ID va parol orqali boshqa talaba ro‘yxatdan o‘tgan bo‘ladi. Bunday holatda siz fakultet dekanatiga murojaat qilishingiz kerak.\n\n*ID yoki parolingiz xato iltimos qaytadan urinib ko‘ring*\ndegan xabar kelsa demak siz ID yoki parolni noto‘g‘ri kiritgansiz. Iltimos, qaytadan urinib ko‘ring.\n\n*Ro‘yxatdan o‘tish muvaffaqiyatli amalga oshirildi!* xabari kelgandagina siz ro‘yxatdan muvaffaqiyatli o‘tgan bo‘lasiz\n\nDarsingiz tugagan vaqtda 1 dan 5 gacha baho berish uchun xabar keladi va baho berganingizdan so‘ng\n\n*Dars va ustoz haqida fikr va takliflaringizni yuboring.* degan xabar keladi bu holatda har qanday fikr va takliflaringizni yuborishingiz shart aks holda bergan bahoiyingiz qabul qilinmaydi.❗\n\nSavollaringiz bo'lsa https://t.me/tiiamenru_supportbot ga murojaat qiling",
    "tutorial_message": "Botdan foydalanish uchun ro'yxatdan o'tgan bo'lishingiz kerak.\n\nRo'yxatdan o'tish uchun shaxsiy login raqamingizni yuboring. Bu sizning *HEMIS ID* raqamingiz hisoblanadi\n\nKeyingi qadamda parolingizni yuboring.\n\nParol bu sizning pasport seriya raqamingiz hisoblanadi.  Misol uchun: *AA1234567*\n\nAgar siz ro'yxatdan o'tgan bo'lsangiz, bot sizga ma'lumotlaringizni ko'rsatadi.\n\nAgar siz ro'yxatdan o'tmagan bo'lsangiz, bot sizni ro'yxatdan o'tishga chaqiradi.\n\n*Agar sizga darsingiz yo'q vaqtda baho berish uchun xabar yuborilsa iltimos buni bee'tibor qoldiring.❗️❗️*",
    "feedback_prompt": "Dars va ustoz haqida fikr va takliflaringizni yuboring❗",
    "finish_message": "*Baholar qabul qilindi*, E'tiboringiz uchun rahmat!👍",
    "rating_message": "📚 Fan: *{lesson_name}*\n👨‍🏫 Ustoz: *{teacher_name}*\n🚪Xona: *{class_['room']}*\n\nUstozning pedagogik mahoratiga baho bering❗👇",
    "about_message": "Ism: ```{result[0]}```\nFamiliya: ```{result[1]}```\nGuruh: ```{result[2]}```\nKurs: ```{result[3]}```\nTelegram id: ```{result[4]}```"
}
english = {
    "greeting": "Hello.",
    "login_prompt": "Please enter your personal login ID❗",
    "password_prompt": "Please enter your password❗",
    "login_success": "Registration successful❗",
    "already_registered": "You are already registered❗",
    "user_exists": "User already exists❗\n\nPress /start command to try again.",
    "login_error": "Incorrect ID or password, please try again❗\n\nPress /start command to try again.",
    "about_not_registered": "You are not registered❗ Please use the /start command.",
    "help_message": "This bot is designed for monitoring educational quality and rating teachers.\n\nUse the following commands:\n\n/start - Start the bot\n/about - View your information\n/tutorial - Bot usage tutorial\n/help - Help\n/lang - Change language\n\nIf you receive a message stating *Such a user exists* it means that another user has already registered using the same ID and password. In such a case, you need to contact the faculty dean.\n\nIf you receive the message *Your ID or password is incorrect, please try again* it means you have entered the wrong ID or password. Please try again.\n\nRegistration is successful! You will receive this message when you have successfully registered.\n\nWhen the time for rating expires, you will receive a message to rate from 1 to 5, and after you give your rating\n\nSend your feedback and suggestions about the class and teacher. This message is received when you need to send any feedback or suggestions; otherwise, your given score will not be accepted.❗\n\nIf you have any questions, please contact https://t.me/tiiamenru_supportbot",
    "tutorial_message": "To use the bot, you need to register.\n\nEnter your personal login ID. This is your *HEMIS ID*\n\nNext, enter your password.\n\nYour password is your passport serial number. For example: *AA1234567*\n\nIf you are registered, the bot will display your information.\n\nIf you are not registered, the bot will prompt you to register.\n\n*Please note that if you receive a message to rate within the allotted time, pay attention to it.❗️❗️*",
    "feedback_prompt": "Send your feedback and suggestions about the class and teacher❗",
    "finish_message": "*Ratings received*, Thank you for your attention!👍",
    "rating_message": "📚 Lesson: *{lesson_name}*\n👨‍🏫 Teacher: *{teacher_name}*\n🚪Room: *{class_['room']}*\n\nRate the teacher's pedagogical skills❗👇",
    "about_message": "Name: ```{result[0]}```\nSurname: ```{result[1]}```\nGroup: ```{result[2]}```\nCourse: ```{result[3]}```\nTelegram id: ```{result[4]}```"
}
russian = {
    "greeting": "Добро пожаловать.",
    "login_prompt": "Пожалуйста, введите ваш личный логин ID❗",
    "password_prompt": "Пожалуйста, введите ваш пароль❗",
    "login_success": "Регистрация успешна❗",
    "already_registered": "Вы уже зарегистрированы❗",
    "user_exists": "Пользователь уже существует❗\n\nНажмите команду /start, чтобы попробовать снова.",
    "login_error": "Неправильный ID или пароль, пожалуйста, попробуйте снова❗\n\nНажмите команду /start, чтобы попробовать снова.",
    "about_not_registered": "Вы не зарегистрированы❗ Пожалуйста, используйте команду /start.",
    "help_message": "Этот бот предназначен для отслеживания качества образования и оценки преподавателей.\n\nИспользуйте следующие команды:\n\n/start - Начать бота\n/about - Просмотреть вашу информацию\n/tutorial - Руководство по использованию бота\n/help - Помощь\n/lang — Сменить язык\n\nЕсли вы получите сообщение *Такой пользователь существует* это означает, что другой пользователь уже зарегистрировался, используя тот же ID и пароль. В таком случае вам следует обратиться к деканату факультета.\n\nЕсли вы получите сообщение *Ваш идентификатор или пароль неверны, попробуйте еще раз.* это означает, что вы ввели неверный ID или пароль. Пожалуйста, попробуйте снова.\n\nРегистрация успешна! Вы получите это сообщение, когда успешно зарегистрируетесь.\n\nКогда истекает время для оценки, вы получите сообщение с запросом оценить от 1 до 5, и после того, как вы дадите свою оценку\n\nОтправьте свой отзыв и предложения о занятии и преподавателе. Это сообщение приходит, когда вам нужно отправить любой отзыв или предложение; в противном случае ваша оценка не будет принята.❗\n\nЕсли у вас есть вопросы, обратитесь к https://t.me/tiiamenru_supportbot",
    "tutorial_message": "Для использования бота вам необходимо зарегистрироваться.\n\nВведите ваш личный логин ID. Это ваш *HEMIS ID*\n\nЗатем введите ваш пароль.\n\nВаш пароль - это серийный номер вашего паспорта. Например: *AA1234567*\n\nЕсли вы зарегистрированы, бот отобразит вашу информацию.\n\nЕсли вы не зарегистрированы, бот пригласит вас зарегистрироваться.\n\n*Пожалуйста, обратите внимание, что если вы получите сообщение оценить в отведенное время, обратите на это внимание.❗️❗️*",
    "feedback_prompt": "Отправьте свой отзыв и предложения о занятии и преподавателе❗",
    "finish_message": "*Получены оценки*, Спасибо за внимание!👍",
    "rating_message": "📚 Урок: *{lesson_name}*\n👨‍🏫 Преподаватель: *{teacher_name}*\n🚪Кабинет: *{class_['room']}*\n\nОцените педагогические навыки преподавателя❗👇",
    "about_message": "Имя: ```{result[0]}```\nФамилия: ```{result[1]}```\nГруппа: ```{result[2]}```\nКурс: ```{result[3]}```\nTelegram id: ```{result[4]}```"
}
japanese = {
    "greeting": "こんにちは。",
    "login_prompt": "個人のログインIDを入力してください❗",
    "password_prompt": "パスワードを入力してください❗",
    "login_success": "登録に成功しました❗",
    "already_registered": "すでに登録されています❗",
    "user_exists": "ユーザーはすでに存在します❗\n\nもう一度やり直すには/startコマンドを押してください。",
    "login_error": "IDまたはパスワードが間違っています、もう一度やり直してください❗\n\nもう一度やり直すには/startコマンドを押してください。",
    "about_not_registered": "登録されていません❗ /startコマンドを使用してください。",
    "help_message": "このボットは教育の質を監視し、教師を評価するために設計されています。\n\n次のコマンドを使用してください:\n/start - ボットを起動する\n/about - あなたの情報を見る\n/tutorial - ボットの使用方法\n/help - ヘルプ\n/lang - 言語を変更する\n\n「そんなユーザーがいる」というメッセージを受け取った場合、別のユーザーが同じIDとパスワードを使用してすでに登録されていることを意味します。この場合、学部の学部長に連絡する必要があります。\n\n「IDまたはパスワードが間違っていますので、もう一度お試しください。」というメッセージを受け取った場合、間違ったIDまたはパスワードを入力したことを意味します。もう一度やり直してください。\n\n登録が成功すると、このメッセージが表示されます。\n\n評価の期限  が切れると、1から5までの評価を求めるメッセージが表示され、評価を行った後\n\n授業や教師に関するフィードバックや提案を送信してください。これは、フィードバックや提案を送信する必要がある場合に受け取るメッセージです。それ以外の場合、あなたの評価は受け入れられません。❗\n\n質問がある場合は、  https://t.me/tiiamenru_supportbot  にお問い合わせください。",
    "tutorial_message": "ボットを使用するには、登録する必要があります。\n\n個人のログインIDを入力してください。これはあなたの*HEMIS ID*です。\n\n次に、パスワードを入力してください。\n\nパスポートのシリアル番号がパスワードです。例: *AA1234567*\n\n登録されている場合、ボットはあなたの情報を表示します。\n\n登録されていない場合、ボットは登録するように促します。\n\n*割り当てられた時間内に評価するように求められた場合は、それに注意してください。❗️❗️*",
    "feedback_prompt": "授業や教師に関するフィードバックや提案を送信してください❗",
    "finish_message": "*評価を受け取りました*、ご注意いただきありがとうございます！👍",
    "rating_message": "📚 レッスン: *{lesson_name}*\n👨‍🏫 教師: *{teacher_name}*\n🚪部屋: *{class_['room']}*\n\n教師の教育スキルを評価してください❗👇",
    "about_message": "名前: ```{result[0]}```\n姓: ```{result[1]}```\nグループ: ```{result[2]}```\nコース: ```{result[3]}```\nTelegram id: ```{result[4]}```"
}
